name: Deploy App to 53
# on: [push] #Toutes les branches
on: 
  push:
    branches:
      - pers_2 # uniquement la branche main
jobs: 
  deploy: # nom du jobs
    runs-on: ubuntu-latest # instance temporaire
    steps: 
    - name: checkout code
      uses: actions/checkout@v4
      # with: 
      #    node-version: '14'
      #    run: npm install -g bats
      #    run: bats -v
