name: 'Deployement App S3'

on: 
  push:
    branches:
      - pers_1
jobs:
  deployement:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: List directory
         run:
          ls -la